# Generated by Django 5.2.13 on 2026-05-03 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_voice_channel",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"kind": "voice"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_voice_users",
                to="chat.channel",
            ),
        ),
    ]
