# Generated by Django 5.2.13 on 2026-05-03 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_channel_audience_and_kind'),
        ('chat', '0002_initial'),
    ]

    operations = [
    ]
