# Generated by Django 5.2.13 on 2026-05-26 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_channel_moderators"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="banned_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="banned_channels",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
